latency: 0
errors: 0
service:
  name: "-"
  pod: "-"
  namespace: "-"
  revision: "-"
  cluster: "-"
spring:
  jackson:
    serialization:
      indent_output: true
logging.pattern.level: "%5p [trace/span:%X{traceId:-},%X{spanId:-}]"
logging.level.io.tetrate: DEBUG
management:
  zipkin:
    tracing:
      endpoint: http://zipkin.istio-system:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0